server:
  port: 10000
  ssl:
    key-store: "/etc/letsencrypt/live/taishonet.com/keystore.p12"
    key-store-password: taisho6339
    keyStoreType: PKCS12
    key-alias: tomcat
security:
  require-ssl: true