server:
  port: 443
  ssl:
    key-store: "/etc/letsencrypt/live/taishonet.com/keystore.p12"
    key-store-password: taisho6339
    keyStoreType: PKCS12
    key-alias: tomcat
    key-password: taisho6339
    ciphers: ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA
    protocol: TLS
security:
  require-ssl: true