server:
  port: 10000
spring:
  redis:
    host: 127.0.0.1
    port: 26379
line:
  bot:
    channelSecret: ab0cde8418d11b9f8203d0fcbef57095
    channelToken: EEkyOew4mBq2FP8H/FExn1pRy8vIOcrqXTFO7xl05ns4bXEDcOc5v2DHghSTZ1165BxNsjF3i7PDPCyldrZplMiT4JpN2BWAM4rp9Abjdm3MXUBfPZkqJcYwW8bkDY7NFEvxBzetzfPPvN9iNvm77wdB04t89/1O/w1cDnyilFU=
#  ssl:
#    key-store: "/etc/letsencrypt/live/taishonet.com/keystore.p12"
#    key-store-password: taisho6339
#    keyStoreType: PKCS12
#    key-alias: tomcat
#    key-password: taisho6339
#security:
#require-ssl: true