server:
  port: 10000
line:
  bot:
    channelSecret: 2b7c3ef6df84e60406d3e13051a6c95a
    channelToken: geQoaqxQA2Nd9E9bKrCWZDuoFi/7+1GSkxJH8B3EFA3GYPGZv0gjPGfprECrOS2nysbzH9XJqZWm3KQnJWORJveMcEBOJvWrl/MG5CwxU8d5U59aWUAas6ALqwwt+H/yid8dfKwQKtyehLnooNw1oAdB04t89/1O/w1cDnyilFU=
#  ssl:
#    key-store: "/etc/letsencrypt/live/taishonet.com/keystore.p12"
#    key-store-password: taisho6339
#    keyStoreType: PKCS12
#    key-alias: tomcat
#    key-password: taisho6339
#security:
#require-ssl: true